- README.md
- lib/myxql/protocol/values.ex
- test/myxql/protocol/values_test.exs
For mysql it is possible to use zero dates and datetimes if the
sql_mode is not set to strict.
https://dev.mysql.com/doc/refman/8.0/en/datetime.html
If we raise then the full query to sql will fail and the user will not
be able to retreive anything.
It should be up to the user to decide how to handle datetime columns
when not in strict mode.
Solves #65
> Zero-datetime decoding

- README.md
Got confused initially by the "requires ... SSL connection" note -- my brain parsed it as another bullet point (that for some reason failed to be displayed as a proper bullet point as the ones above it), and so initially I thought that myxql requires a secure connection always.
I think it's not too far-fetched that others might parse the note similarly, so I'm suggesting to clarify it so no misunderstandings will occur from that.
> clarify note about SSL connection requirement

- lib/myxql/connection.ex
- test/myxql/sync_test.exs
- test/myxql_test.exs
As discussed with @josevalim [here](https://github.com/elixir-ecto/myxql/issues/80#issuecomment-548288007) we are seeing a performance regression in some cases due to no longer having an LRU cache, which Mariaex does have. José mentioned Postgrex reuses repeated prepared statements, which is what this PR implements.
Of course I am open to other implementations. I have not looked at the Postgrex code because augmenting the `last_ref` seemed easier, but if Postgrex has a better way of accomplishing this then I'm willing to take a look there.
> Reuse repeated prepared statements in unnamed mode

- README.md
- lib/myxql/protocol/values.ex
- mix.exs
> Make geo optional

- lib/myxql/client.ex
- lib/myxql/protocol.ex
- test/myxql/protocol/values_test.exs
Closes #10 
This approach assumes that there's always more data to receive if the current packet's payload size is exactly equal to max packet size (16MB) - which is in agreement with specification at https://dev.mysql.com/doc/internals/en/sending-more-than-16mbyte.html. The tests seem to confirm that (when working on the change, I've sprinkled IO.inspects when running the tests to see which `recv_packets` clauses are called for various payload sizes, including exact multiples of max packet size; also, when adjusting the test to make the payload fix exactly at max packet size, the next successful data fetch returns a payload with size 0).
> Support receiving packets larger than 16MB

- mix.exs
- test/myxql/sync_test.exs
Previously we had some extra code inspired by
https://github.com/elixir-ecto/postgrex/pull/325.
We now think that it's reasonable to require that the user of myxql has
:ssl installed.
> Require :ssl & :public_key applications

- lib/myxql/client.ex
- lib/myxql/connection.ex
Previously we had `:ok = send_com(...)` which crashes when we got a socket error, e.g.: `{:error, :closed}`. Now, if we stumble upon that we turn it into `{:disconnect, exception, state}` so the connection can be properly restarted.
closes #111
> Handle socket errors when closing statements

- lib/myxql.ex
I've stumbled upon this issue when working directly with the library. The type spec for `MyXQL.stream/4` was missing `max_rows` in options definition.
> Fix typespec for MyXQL.stream/4

- lib/myxql/protocol/values.ex
- test/myxql/protocol/values_test.exs
This allows `:zero_date` and `:zero_datetime` to be written back to the DB. My app has `ALLOW_INVALID_DATES` enabled, and other portions of the platform are relying on the date `0000-00-00` to be there. So while decoding of these dates (and timestamps) was already handled by myxql, there was nothing in place to allow writing of these values.
In my case with this change, I have implemented a custom ecto type whose `dump` method looks for a "magic" value and when it sees that value will return `{:ok, :zero_date}` and `0000-00-00` will be correctly written to the db.
> encode :zero_datetime and :zero_date

- lib/myxql/connection.ex
If the connection drops, the ETS tables were kept and the number of tables would increase for every disconnection.
The following PR deletes the table using the disconnect callback from DBConnection and the table will be recreated when the connection is established.
> Delete table on disconnect

- lib/myxql/protocol/auth.ex
- test/myxql/client_test.exs
- test/test_helper.exs
An argument error is encountered when trying to authenticate with a sha256 or caching_sha2 password longer than 20 bytes:
```
20:49:08.828 [error] GenServer #PID<0.406.0> terminating
** (ArgumentError) argument error
(stdlib 3.5) :binary.part(<<105, 5, 61, 82, 25, 87, 87, 33, 9, 14, 54, 64, 20, 74, 2, 93, 37, 68, 77, 111>>, 0, 50)
(myxql 0.3.4) lib/myxql/protocol/auth.ex:19: MyXQL.Protocol.Auth.encrypt_sha_password/3
(myxql 0.3.4) lib/myxql/client.ex:402: MyXQL.Client.perform_public_key_auth/5
(myxql 0.3.4) lib/myxql/client.ex:271: MyXQL.Client.do_handshake/2
(myxql 0.3.4) lib/myxql/client.ex:252: MyXQL.Client.handshake/2
(myxql 0.3.4) lib/myxql/connection.ex:32: MyXQL.Connection.connect/1
(db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2 …
```
> Support long passwords (sha256 and caching_sha2)

- lib/myxql/protocol.ex
- test/myxql/client_test.exs
- test/test_helper.exs
This is an attempt at fixing https://github.com/elixir-ecto/myxql/issues/140.
The error occurs because the stored procedure uses a cursor and tries to return a result. This means after the `column_defs_eof` message, there is still more data and causes the `"" = next_data` match to fail.
This change will allow the stored procedure to perform the cursor operations and still return the result. In the test you can see that the cursor operations happened because the correct value is returned in the final select statement.
All the tests pass, but I'm not sure if there could be scenarios where the cursor flag is set and you need to raise an error when `next_data != ""`. If there are then this PR would need modification.
> stored procedures with cursor result

- lib/myxql.ex
- lib/myxql/connection.ex
- test/myxql_test.exs
There is some cache behaviour I noticed when studying the code. Some of it is document and some of it isn't. I think there might be some improvements that could be made. I tried looking through the PR/issue history to see if these changes were already considered and didn't find anything. I apologize if I missed it.
Undocumented behaviour:
- Using both the `MyXQL.prepare` and `MyXQL.query` functions with the same query name will cause a match error in `Connection.queries_get`
Documented behaviour:
- If you prepare a query with an already existing name using `MySQL.prepare` it will use the cached value and not update it.
This PR is suggesting to remove `cache: :reference` and make them all statement caches. My rationale is that it better matches the behaviour of the `PREPARE` command in …
> cache changes

- lib/myxql.ex
- lib/myxql/client.ex
- lib/myxql/connection.ex
- lib/myxql/protocol.ex
- lib/myxql/query.ex
- lib/myxql/text_query.ex
- test/myxql/client_test.exs
- test/myxql/sync_test.exs
- test/myxql_test.exs
Closes https://github.com/elixir-ecto/myxql/issues/143
Introduces new functions `query_many`, `prepare_many`, `prepare_execute_many` and `execute_many` that allow the user to obtain results for queries that return multiple results, like text queries with multiple statements or stored procedures.
The main idea is:
-  Introduce 2 new structs: MyXQL.Queries and MyXQL.TextQueries 
-  Keep a result state in addition to the decoder state while receiving the packets. 
- The result state will keep track of whether this is a single or multiple result and if multiple, store the results already obtained. 
- This lets us decide whether or not to keep going when MySQL says there are more results. And if we are retrieving multiple results to keep the partial results stored somewhere.
-  Keeping this …
> query many

- lib/myxql/connection.ex
- test/myxql/sync_test.exs
- test/myxql_test.exs
This continues the work of @hkrutzer  in https://github.com/elixir-ecto/myxql/pull/126 and https://github.com/elixir-ecto/myxql/pull/92.
The idea is to cache the last prepared query in unnamed mode and reuse it when you can. To summarize:
For unnamed:
- don't immediately close the query
- close the last query on new prepare or execution of a different query
For named:
- keep the same behaviour immediately closing queries with "" name (i.e. if they call query without specifying cache_statement).
> Prepare unnamed reuse statements

- lib/myxql/error.ex
- test/myxql_test.exs
Adds the query statement to the error log. This is similar to the implementation from Postgrex.
> print query statement in error log

- .github/workflows/ci.yml
- lib/myxql/protocol/auth.ex
- lib/myxql/protocol/server_error_codes.ex
Deprecation
- Elixir 1.14 - `use Bitwise` is deprecated
- Elixir 1.10 - `Application.compile_env/3` is introduced
Also add Elixir 1.14.1 & OTP 25.1.2 to CI
> do not use deprecated features by Elixir version

- lib/myxql/connection.ex
so db_connection caller will be able to execute rollback for a failed `commit` operation or disconnect a given connection for a failed `begin` or `rollback` operation.
More information in https://github.com/elixir-ecto/db_connection/issues/272
> Return {status, state} on transaction error

- lib/myxql.ex
- lib/myxql/client.ex
- lib/myxql/protocol/auth.ex
- lib/myxql/protocol/types.ex
- test/myxql/client_test.exs
- test/myxql_test.exs
Took me a minute to figure out why my app kept crashing in ECS :smile:
RDS IAM auth requires the generated auth token to be send as a cleartext password with MySQL. I'm replicating how [mysql-client](https://dev.mysql.com/doc/refman/8.0/en/cleartext-pluggable-authentication.html) enables  cleartext password in this PR.
There wasn't a way to integrate the tests with actual MySQL containers, since all plugins that support cleartext are in the enterprise edition, so I'm mocking the responses after introspecting mysql packets.
I'm currently using this branch in AWS.
> Enable cleartext plugin

- lib/myxql/protocol.ex
- lib/myxql/protocol/flags.ex
Closes https://github.com/elixir-ecto/myxql/issues/173
Previously, during the initial handshake the library would error if the client and server capabilities didn't match. However, the MySQL spec says the client should simply remove the flags the server can't comply with: https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html.
It seems this part of the code was reusing a function that tried to ensure all the appropriate auth capabilities were present: https://github.com/elixir-ecto/myxql/blob/master/lib/myxql/protocol.ex#L116.
The change here is to introduce a filtering function instead of using the "ensure everything allowed" function.
> Filter client capabilities that can't be met by server

- lib/myxql/result.ex
When I was attempting to see the warnings from a query I got this error using the binary protocol:
```elixir
** (MyXQL.Error) (1295) (ER_UNSUPPORTED_PS) This command is not supported in the prepared statement protocol yet
query: SHOW WARNINGS
```
> Update show warnings example to use text protocol

- .github/workflows/ci.yml
- lib/myxql.ex
- lib/myxql/client.ex
- lib/myxql/protocol.ex
- lib/myxql/protocol/auth.ex
- test/myxql/client_test.exs
- test/myxql_test.exs
- test/test_helper.exs
Similar to https://github.com/elixir-ecto/postgrex/pull/677
Closes #61
> Streamline SSL experience

- test/myxql_test.exs
Closes https://github.com/elixir-ecto/myxql/issues/190
Based on [this update](https://mariadb.com/kb/en/prepare-statement/#permitted-statements), it seems fewer statements are not able to be prepared. I just changed it to one that still cannot be prepared.
> Make non preparable statement test compatible with future mariadb

- lib/myxql/connection.ex
- test/myxql_test.exs
Closes https://github.com/elixir-ecto/myxql/issues/193
There are still a lot of other weird situations where query_many will break, [see here](https://github.com/elixir-ecto/myxql/pull/152/files). But this will fix the use case in the issue. If there is interest, we can continue fixing query_many completely but I need some time to play with the old PR to understand what was happening.
> Handle insert/update/delete responses in query_many

- mix.exs
Relax the Geo dependency so we can use this lib with Geo ~> V4.0.
> permit geo ~> V4.0
